name: Setup Python and uv
description: Sets up Python, uv with caching, and installs project dependencies

inputs:
  python-version:
    description: Python version to install
    required: true
  dependency-groups:
    description: Dependency groups to install (space-separated, e.g., "dev test")
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up uv with caching
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: |
        if [ -n "${{ inputs.dependency-groups }}" ]; then
          # Install specific groups
          groups="${{ inputs.dependency-groups }}"
          group_args=""
          for group in $groups; do
            group_args="$group_args --group $group"
          done
          uv sync $group_args
        else
          # Install all groups
          uv sync --all-groups
        fi
